include: package:dartwindows_lints/analysis_options.yaml

analyzer:
  exclude: ['test_fixes/**']
  errors:
    todo: ignore

linter:
  rules:
    # Unnecessary in most cases, but avoids accidental name clashes.
    unnecessary_this: false
