// isensordatareport.dart

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'dart:ffi';

import '../extensions/iunknown.dart';
import '../propertykey.dart';
import '../structs.g.dart';
import '../types.dart';
import '../utils.dart';
import '../variant.dart';
import 'iunknown.dart';

/// @nodoc
const IID_ISensorDataReport = '{0ab9df9b-c4b5-4796-8898-0470706a2e1d}';

/// Represents a sensor data report. Sensor data reports contain data field
/// values generated by a sensor and a time stamp that indicates when the
/// data report was created.
///
/// {@category com}
class ISensorDataReport extends IUnknown {
  ISensorDataReport(super.ptr)
      : _vtable = ptr.value.cast<ISensorDataReportVtbl>().ref;

  final ISensorDataReportVtbl _vtable;

  factory ISensorDataReport.from(IUnknown interface) =>
      ISensorDataReport(interface.toInterface(IID_ISensorDataReport));

  int getTimestamp(Pointer<SYSTEMTIME> pTimeStamp) =>
      _vtable.GetTimestamp.asFunction<
              int Function(VTablePointer, Pointer<SYSTEMTIME> pTimeStamp)>()(
          ptr, pTimeStamp);

  int getSensorValue(Pointer<PROPERTYKEY> pKey, Pointer<PROPVARIANT> pValue) =>
      _vtable.GetSensorValue.asFunction<
          int Function(VTablePointer, Pointer<PROPERTYKEY> pKey,
              Pointer<PROPVARIANT> pValue)>()(ptr, pKey, pValue);

  int getSensorValues(VTablePointer pKeys, Pointer<VTablePointer> ppValues) =>
      _vtable.GetSensorValues.asFunction<
          int Function(VTablePointer, VTablePointer pKeys,
              Pointer<VTablePointer> ppValues)>()(ptr, pKeys, ppValues);
}

/// @nodoc
base class ISensorDataReportVtbl extends Struct {
  external IUnknownVtbl baseVtbl;
  external Pointer<
          NativeFunction<
              Int32 Function(VTablePointer, Pointer<SYSTEMTIME> pTimeStamp)>>
      GetTimestamp;
  external Pointer<
      NativeFunction<
          Int32 Function(VTablePointer, Pointer<PROPERTYKEY> pKey,
              Pointer<PROPVARIANT> pValue)>> GetSensorValue;
  external Pointer<
      NativeFunction<
          Int32 Function(VTablePointer, VTablePointer pKeys,
              Pointer<VTablePointer> ppValues)>> GetSensorValues;
}

/// @nodoc
const CLSID_SensorDataReport = '{4ea9d6ef-694b-4218-8816-ccda8da74bba}';

/// {@category com}
class SensorDataReport extends ISensorDataReport {
  SensorDataReport(super.ptr);

  factory SensorDataReport.createInstance() => SensorDataReport(
      createCOMObject(CLSID_SensorDataReport, IID_ISensorDataReport));
}
