name: flutter_runner
description: A Dart library for accessing common Win32 APIs using FFI. No C required!
version: 0.0.1
homepage: https://timsneath.github.io/win32/flutter_runner
repository: https://github.com/timsneath/win32/
issue_tracker: https://github.com/timsneath/win32/issues
documentation: https://timsneath.github.io/win32/
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  win32:
    path: ./../
  args: ^2.2.0

dev_dependencies:
  lint: ^1.2.0
  meta: ^1.7.0
  test: ^1.17.10
