name: generator
description: >
  Auto-generate Dart wrapper classes for the Win32 API using Windows metadata.
publish_to: none

environment:
  sdk: ^3.4.0-0

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.3.6

  # Help ensure that the code is well-written.
  dartwindows_lints: ^1.1.0

  # Foreign Function Interface extension methods.
  ffi: ^2.1.2

  # For manipulating paths.
  path: ^1.9.0

  # Running the test suite.
  test: ^1.25.2

  # Windows metadata for automatically generating API signatures.
  winmd: ^4.1.0

  # Win32 itself.
  win32: ^5.2.0

dev_dependencies:
  meta: ^1.12.0
