name: win32gen
description: Auto-generate Dart wrapper classes for the Win32 API using Windows metadata
publish_to: none

environment:
  sdk: '^3.1.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.3.2

  # Foreign Function Interface extension methods
  ffi: ^2.1.0

  # Help ensure that the code is well-written.
  lints: ^2.1.1

  # Running the test suite.
  test: ^1.24.6

  # Windows metadata for automatically generating API signatures.
  winmd: ^4.0.1

  # Win32 itself
  win32: ^5.0.7
